namespace: "vimalmenon"

apps:
  - name: frontend-vimalmenon
    tyre: frontend
    port: 3000
    deployment:
      replicas: 1
      image: vimalsmenon/frontend.vimalmenon.com
      version: Dev
      imagePullPolicy: Always
    service:
      type: NodePort
      targetPort: 3000
      nodePort: 30000
    ingress:
      url: vimalmenon.local
      port: 80
  - name: api-vimalmenon
    tyre: api
    port: 8000
    deployment:
      replicas: 1
      image: vimalsmenon/api.vimalmenon.com
      version: Dev
      imagePullPolicy: Always
    service:
      type: ClusterIp
    ingress:
      url: api.vimalmenon.local
      port: 80

