namespace: "vimalmenon"

apps:
  - name: frontend-vimalmenon
    tyre: frontend
    deployment:
      replicas: 1
      image: vimalsmenon/frontend.vimalmenon.com
      version: Dev
      imagePullPolicy: Always
      port: 3000
    service:
      type: NodePort
      targetPort: 3000
      nodePort: 30000
  - name: api-vimalmenon
    tyre: api
    deployment:
      replicas: 1
      image: vimalsmenon/api.vimalmenon.com
      version: Dev
      imagePullPolicy: Always
      port: 8000
    service:
      type: NodePort
      targetPort: 8000
      nodePort: 32000

