namespace: "vimalmenon"
env: Local

namespaceOverride: "monitoring"

apps:
  - name: frontend-vimalmenon
    tyre: frontend
    port: 3000
    deployment:
      replicas: 1
      image: vimalsmenon/frontend.vimalmenon.com
      imagePullPolicy: Always
    service:
      type: ClusterIp
    ingress:
      url: vimalmenon.local
      port: 80
    configMap:
      NEXT_PUBLIC_ENV: Local
      NEXT_PUBLIC_API: http://api-vimalmenon-service
  - name: api-vimalmenon
    tyre: api
    port: 8000
    deployment:
      replicas: 1
      image: vimalsmenon/api.vimalmenon.com
      imagePullPolicy: Always
    service:
      type: ClusterIp
    ingress:
      url: api.vimalmenon.local
      port: 80
    configMap:
      ENV: Local

