{{- $root := . -}}

{{- range $v := .Values.apps}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $v.name }}-deploy
    tyre: {{ $v.tyre }}
  name: {{ $v.name }}-deploy
  namespace: {{ $root.Values.namespace }}
spec:
  replicas: {{ $v.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $v.name}}-pod
      tyre: {{ $v.tyre }}
  template:
    metadata:
      labels:
        app: {{ $v.name }}-pod
        tyre: {{ $v.tyre }}
    spec:
      containers:
      - name: {{ $v.name }}-pod
        image: {{ $v.deployment.image }}:{{ $v.deployment.version }}
        imagePullPolicy: {{ $v.deployment.imagePullPolicy }}
        ports:
          - containerPort: {{ $v.deployment.port }}
---
{{- end}}

