{{- $root := . -}}

{{- range $v := .Values.apps}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $v.name }}-node-port-service
  labels:
    type: {{ $v.name }}-node-port-service
    tyre: {{ $v.tyre }}
spec:
  type: {{ $v.service.type }}
  selector:
    app: {{ $v.name}}-pod
  ports: 
    - name: {{ $v.name }}-service
      port: 3000
      targetPort: {{ $v.service.targetPort }}
      nodePort: {{ $v.service.nodePort }}
---
{{- end }}

{{- range $v := .Values.apps}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $v.name }}-service
  labels:
    type: {{ $v.name }}-service
    tyre: {{ $v.tyre }}
spec:
  selector:
    app: {{ $v.name}}-pod
  ports: 
    - name: {{ $v.name }}-service
      port: {{ $v.port }}
      targetPort: {{ $v.port }}
---
{{- end }}
