{{- $root := . -}}

{{- range $v := .Values.apps}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $v.name }}-service
  namespace: {{ $root.Values.namespace }}
  labels:
    type: {{ $v.name }}-service
    tyre: {{ $v.tyre }}
spec:
  selector:
    app: {{ $v.name}}-pod
  ports: 
    - name: {{ $v.name }}-port-service
      port: {{ $v.port }}
      targetPort: {{ $v.port }}
---
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: argo-cd-server
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
---


